### ISSUE TITLE
Compilation Instructions?

### ISSUE THREAD

**Issue by rtlsdrblog** [samwhiting/gnuradio-doa#1]
Very cool presentation at GRcon17!

Would it be possible to get some basic instructions on how to compile and set up your Android app?

**Comment by samwhiting** [comment]
Unfortunately we can't distribute any of the Android app that goes along
with our project, since it's the property of the group funding our
research. The only code available is for the custom gnuradio blocks used in
the direction of arrival analysis.

Sam
